# Generated by Django 6.0.6 on 2026-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=80, unique=True)),
                ('paleta_graficos', models.CharField(choices=[('msm-industrial', 'MSM Industrial'), ('azul-corporativo', 'Azul corporativo'), ('verde-engenharia', 'Verde engenharia'), ('cinza-tecnico', 'Cinza técnico'), ('alto-contraste', 'Alto contraste')], default='msm-industrial', max_length=40)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
    ]
