# Generated by Django 6.0.6 on 2026-06-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Nº Contrato')),
                ('empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('objeto', models.TextField(blank=True, verbose_name='Objeto')),
                ('valor_contratual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Contratual')),
                ('total_aditivos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Aditivos')),
                ('total_reajustamento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de Reajustamento')),
                ('reequilibrio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Reequilíbrio')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('garantia', models.CharField(blank=True, max_length=100, verbose_name='Garantia')),
                ('data_inicio', models.CharField(blank=True, max_length=30, verbose_name='Data Início')),
                ('data_fim', models.CharField(blank=True, max_length=30, verbose_name='Data Fim')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('percentual_executado', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='% Executado')),
                ('valor_msm_a_executar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor MSM a Executar')),
                ('valor_csm_a_executar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor CSM a Executar')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['numero_contrato'],
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_medicao', models.CharField(max_length=50, verbose_name='Nº Medição')),
                ('numero_contrato', models.CharField(max_length=50, verbose_name='Nº Contrato')),
                ('mes_ano', models.CharField(blank=True, max_length=20, verbose_name='Mês/Ano')),
                ('valor_medido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Medido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Pago')),
                ('data_pagamento', models.CharField(blank=True, max_length=30, verbose_name='Data Pagamento')),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Liquidado')),
                ('valor_faturado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Faturado')),
                ('data_faturamento', models.CharField(blank=True, max_length=30, verbose_name='Data Faturamento')),
                ('valor_a_processar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Medições a Processar')),
                ('situacao', models.CharField(blank=True, max_length=50, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
                'ordering': ['numero_contrato', 'numero_medicao'],
            },
        ),
    ]
