# Generated by Django 6.0.6 on 2026-06-29 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('automatica_navegador', 'Automática pelo navegador'), ('automatica_servidor', 'Automática pelo servidor')], default='manual', max_length=50, verbose_name='Origem')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], default='sucesso', max_length=20, verbose_name='Status')),
                ('total_contratos', models.IntegerField(default=0, verbose_name='Total de contratos')),
                ('total_medicoes', models.IntegerField(default=0, verbose_name='Total de medições')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de sincronização',
                'verbose_name_plural': 'Histórico de sincronizações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
